### PR TITLE
mini optimize the tos_sem.c

### PR DESCRIPTION
**Pull request by DavidLin1577**

### CODE REVIEW

**Comment by daishengdong** [comment]
代码风格请保持与现内核一致

**Comment by daishengdong** [comment]
而且逻辑也应该是init_count > max_count的话，将init_count赋值为max_count，而并非默认把max扩大，同时相关判断语句加上unlikeyly优化

**Comment by daishengdong** [comment]
__API__ k_err_t tos_sem_create_max(k_sem_t *sem, k_sem_cnt_t init_count, k_sem_cnt_t max_count)
{
    TOS_PTR_SANITY_CHECK(sem);

    if (unlikely(init_count > max_count)) {
        init_count = max_count;
    }

    sem->count      = init_count;
    sem->count_max  = max_count;

    pend_object_init(&sem->pend_obj);
    TOS_OBJ_INIT(sem, KNL_OBJ_TYPE_SEMAPHORE);

**Comment by DavidLin1577** [comment]
> 而且逻辑也应该是init_count > max_count的话，将init_count赋值为max_count，而并非默认把max扩大，同时相关判断语句加上unlikely优化

了解，谢谢。

**Comment by DavidLin1577** [comment]
> **API** k_err_t tos_sem_create_max(k_sem_t *sem, k_sem_cnt_t init_count, k_sem_cnt_t max_count)
> {
> TOS_PTR_SANITY_CHECK(sem);
> 
> ```
> if (unlikely(init_count > max_count)) {
>     init_count = max_count;
> }
> 
> sem->count      = init_count;
> sem->count_max  = max_count;
> 
> pend_object_init(&sem->pend_obj);
> TOS_OBJ_INIT(sem, KNL_OBJ_TYPE_SEMAPHORE);
> ```

已按建议更新。

**Pull request merged**
